# Generated by Django 2.0.3 on 2018-03-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField()),
                ('population', models.IntegerField()),
                ('persons_per_household', models.FloatField()),
                ('average_house_value', models.FloatField()),
                ('income_per_household', models.FloatField()),
                ('electricity', models.FloatField()),
                ('nat_gas', models.FloatField()),
                ('fuel_oil', models.FloatField()),
                ('vehic_miles_traveled', models.FloatField()),
                ('transport', models.FloatField()),
                ('housing', models.FloatField()),
                ('food', models.FloatField()),
                ('goods', models.FloatField()),
                ('services', models.FloatField()),
                ('total_household_footprint', models.FloatField()),
                ('households_per_zipcode', models.IntegerField()),
                ('total_zipcode_footprint', models.FloatField()),
            ],
        ),
    ]
