# Generated by Django 2.0.3 on 2018-03-23 01:06

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(default=30.0, validators=[calc.models.validate_nonnegative])),
                ('rebate_portion', models.FloatField(default=0.7, validators=[calc.models.validate_0to1])),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('gasoline_amt', models.FloatField(validators=[calc.models.validate_nonnegative])),
                ('heating_amt', models.FloatField(validators=[calc.models.validate_nonnegative])),
                ('heating_type', models.CharField(choices=[('gas', 'Natural Gas'), ('fuel', 'Fuel Oil'), ('elec', 'Electricity')], default='gas', max_length=4)),
                ('elec_amt', models.FloatField(validators=[calc.models.validate_nonnegative])),
                ('elec_type', models.CharField(choices=[('pseg', 'PSE&G'), ('rockland', 'Orange Rockland Electric'), ('jcpl', 'Jersey Central Power & Light'), ('atlantic', 'Atlantic City Electric')], default='pseg', max_length=8)),
            ],
        ),
    ]
