# Generated by Django 2.0.3 on 2018-04-08 19:15

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(default=10.0, validators=[calc.models.validate_nonnegative])),
                ('rebate_portion', models.FloatField(default=0.7, validators=[calc.models.validate_0to1])),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=1)),
                ('gasoline_amt', models.FloatField(default=1.0, validators=[calc.models.validate_nonnegative])),
                ('gasoline_type', models.CharField(choices=[('e10', '10% Ethanol'), ('e0', 'Pure Gasoline'), ('diesel', 'Diesel'), ('b20', '20% Biodiesel')], default='e10', max_length=40)),
                ('gasoline_unit', models.CharField(choices=[('gallon', 'gallons')], default=('gallon', 'gallons'), max_length=40)),
                ('elec_amt', models.FloatField(default=1.0, validators=[calc.models.validate_nonnegative])),
                ('elec_type', models.CharField(choices=[('pseg', 'PSE&G'), ('rockland', 'Orange Rockland Electric'), ('jcpl', 'Jersey Central Power & Light'), ('atlantic', 'Atlantic City Electric')], default='pseg', max_length=40)),
                ('elec_unit', models.CharField(choices=[('kWh', 'kWh')], default=('kWh', 'kWh'), max_length=40)),
                ('heating_amt', models.FloatField(default=1.0, validators=[calc.models.validate_nonnegative])),
                ('heating_type', models.CharField(choices=[('gas', 'Natural Gas'), ('fuel', 'Fuel Oil'), ('elec', 'Electricity')], default='gas', max_length=40)),
                ('heating_unit', models.CharField(choices=[('therm', 'therms'), ('gallon', 'gallons'), ('kWh', 'kWh')], default=('therm', 'therms'), max_length=40)),
            ],
        ),
    ]
