# Generated by Django 2.0.3 on 2018-03-27 22:08

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_userprofile_gasoline_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='children',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='elec_amt',
            field=models.FloatField(default=1.0, validators=[calc.models.validate_nonnegative]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gasoline_amt',
            field=models.FloatField(default=1.0, validators=[calc.models.validate_nonnegative]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='heating_amt',
            field=models.FloatField(default=1.0, validators=[calc.models.validate_nonnegative]),
        ),
    ]
