# Generated by Django 2.0.3 on 2018-04-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20180327_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='elec_unit',
            field=models.CharField(choices=[('kWh', 'kWh')], default=('kWh', 'kWh'), max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='heating_unit',
            field=models.CharField(choices=[('therm', 'therms'), ('gallon', 'gallons'), ('kWh', 'kWh')], default=('therm', 'therms'), max_length=6),
        ),
    ]
