# Generated by Django 2.0.3 on 2018-04-04 02:20

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_userprofile_gasoline_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fee',
            field=models.FloatField(default=10.0, validators=[calc.models.validate_nonnegative]),
        ),
    ]
