# Generated by Django 2.0.3 on 2018-04-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20180404_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='period',
            field=models.CharField(choices=[('month', 'Per Month'), ('year', 'Per Year')], default='month', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='children',
            field=models.PositiveIntegerField(default=1, help_text='Members of household under 18.'),
        ),
    ]
