# Generated by Django 2.0.3 on 2018-04-08 18:55

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20180407_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='adults',
            field=models.PositiveIntegerField(default=1, help_text='Members of household 18 and older.', validators=[calc.models.validate_leq20]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='children',
            field=models.PositiveIntegerField(default=0, help_text='Members of household under 18.', validators=[calc.models.validate_leq20]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='elec_type',
            field=models.CharField(choices=[('pseg', 'PSE&G'), ('rockland', 'Orange Rockland Electric'), ('jcpl', 'Jersey Central Power & Light'), ('atlantic', 'Atlantic City Electric')], default='pseg', help_text='Your electric utility provider.', max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fee',
            field=models.FloatField(default=30.0, help_text='Fee, dollars per ton of CO2.', validators=[calc.models.validate_nonnegative]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='period',
            field=models.CharField(choices=[('month', 'Per Month'), ('year', 'Per Year')], default='month', help_text='Time range for calculation.', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rebate_portion',
            field=models.FloatField(default=0.7, help_text='Portion of total revenue. The rest goes to sustainableinvestment and relief for vulnerable businesses and communities.', validators=[calc.models.validate_0to1]),
        ),
    ]
