# Generated by Django 2.0.3 on 2018-04-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20180408_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gasoline_type',
            field=models.CharField(choices=[('e10', '10% Ethanol'), ('e0', 'Pure Gasoline'), ('diesel', 'Diesel'), ('b20', '20% Biodiesel')], default='e10', max_length=9),
        ),
    ]
