# Generated by Django 2.0.3 on 2018-04-11 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_auto_20180411_0024'),
        ('calc', '0009_auto_20180408_1940'),
    ]

    operations = [
    ]
